FROM oven/bun:latest AS base

WORKDIR /app

# install dependencies
FROM base AS install

RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# install production dependencies (without devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --production --frozen-lockfile

FROM base AS prerelease

COPY --from=install /temp/dev/node_modules ./node_modules
COPY . .
RUN bun --bun run build

FROM base AS release

ARG APP_INFORMATIONAL_VERSION=development
ENV PUBLIC_APP_VERSION=$APP_INFORMATIONAL_VERSION

COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /app/build .

USER bun
EXPOSE 3000/tcp

ENTRYPOINT [ "bun", "--bun", "run", "index.js" ]
